import 'dart:io';

import 'dart:math';

// muss über 'dart run loops04.dart' aufgerufen werden
// (aus dem richtigen Verzeichnis)
// Known limitations: Can't go beyond 100

void main() {
  final rng = Random();
  print('Wieviele Würfel sollen geworfen werden? ');
  final input = stdin.readLineSync();
  if (input == null) return;
  final anzahl = int.tryParse(input) ?? 0;
  if (anzahl < 1) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 2) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 3) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 4) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 5) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 6) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 7) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 8) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 9) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 10) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 11) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 12) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 13) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 14) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 15) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 16) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 17) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 18) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 19) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 20) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 21) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 22) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 23) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 24) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 25) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 26) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 27) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 28) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 29) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 30) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 31) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 32) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 33) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 34) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 35) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 36) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 37) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 38) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 39) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 40) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 41) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 42) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 43) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 44) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 45) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 46) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 47) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 48) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 49) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 50) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 51) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 52) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 53) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 54) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 55) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 56) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 57) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 58) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 59) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 60) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 61) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 62) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 63) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 64) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 65) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 66) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 67) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 68) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 69) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 70) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 71) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 72) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 73) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 74) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 75) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 76) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 77) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 78) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 79) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 80) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 81) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 82) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 83) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 84) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 85) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 86) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 87) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 88) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 89) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 90) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 91) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 92) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 93) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 94) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 95) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 96) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 97) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 98) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 99) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
  if (anzahl < 100) return;
  print('Würfelergebnis: ${rng.nextInt(6) + 1}');
}
